/**
 * Named type aliases for the Seam Explorer API schema types.
 *
 * WHY a separate file: types.ts is auto-generated by openapi-typescript and
 * regenerated on every `npm run gen:types` run. Editing it directly would be
 * overwritten. These aliases are stable convenience re-exports that the rest
 * of the codebase imports from.
 *
 * All types are derived from the Pydantic response models in seam/server/web.py.
 */

import type { components } from "./types";

export type StatusResponse = components["schemas"]["StatusResponse"];
export type SearchResultItem = components["schemas"]["SearchResultItem"];
export type SearchResponse = components["schemas"]["SearchResponse"];
export type GraphNode = components["schemas"]["GraphNode"];
export type GraphEdge = components["schemas"]["GraphEdge"];
export type NeighborhoodResponse = components["schemas"]["NeighborhoodResponse"];
export type SymbolDefinition = components["schemas"]["SymbolDefinition"];
export type ClusterInfo = components["schemas"]["ClusterInfo"];
export type WhyComment = components["schemas"]["WhyComment"];
export type SymbolResponse = components["schemas"]["SymbolResponse"];
export type ClusterItem = components["schemas"]["ClusterItem"];
export type ClustersResponse = components["schemas"]["ClustersResponse"];

// ── Phase 2 additions ──────────────────────────────────────────────────────────
export type ImpactEntry = components["schemas"]["ImpactEntry"];
export type ImpactResponse = components["schemas"]["ImpactResponse"];
export type TraceHop = components["schemas"]["TraceHop"];
export type TraceResponse = components["schemas"]["TraceResponse"];
export type ChangedSymbol = components["schemas"]["ChangedSymbol"];
export type AffectedEntry = components["schemas"]["AffectedEntry"];
export type ChangesResponse = components["schemas"]["ChangesResponse"];
export type ConstellationCluster = components["schemas"]["ConstellationCluster"];
export type ConstellationLink = components["schemas"]["ConstellationLink"];
export type ConstellationResponse = components["schemas"]["ConstellationResponse"];
export type HubSymbol = components["schemas"]["HubSymbol"];
export type HubsResponse = components["schemas"]["HubsResponse"];
