/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/graph/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph Search
         * @description Return typed structural graph-search results without source text.
         */
        get: operations["get_graph_search_api_graph_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/architecture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Architecture
         * @description Return a bounded architecture overview that chains into precise Seam tools.
         */
        get: operations["get_architecture_api_architecture_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layout
         * @description Compute a whole-repo 3D constellation layout (server-side positions).
         *
         *     Returns pre-positioned nodes, edges, and cluster summaries for the 3D
         *     Constellation Explorer tab. Positions are deterministic and cached per
         *     (MAX(files.indexed_at), max_nodes) with a TTL of SEAM_STALENESS_TTL_SECONDS.
         *
         *     The O(n²) numpy ForceAtlas2 kernel is only re-run when the index changes or
         *     the cache entry expires. Cluster halos are derived from node positions.
         *
         *     Responds with 503 NO_INDEX when the index does not exist.
         */
        get: operations["get_layout_api_graph_layout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description Return index capability metadata for diagnostics and feature gating.
         */
        get: operations["get_schema_api_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snippet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snippet
         * @description Expose the same exact-source contract to the Explorer without duplicating rules.
         */
        get: operations["get_snippet_api_snippet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Return index statistics and metadata including watcher-aware staleness.
         *
         *     Returns symbol_count, edge_count, cluster_count, last_indexed timestamp,
         *     the list of languages present in the index, and additive stale/stale_reason
         *     fields derived from the same check_staleness() source of truth used by the
         *     MCP graph-traversal handlers — so /api/status never disagrees with seam status.
         */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search
         * @description Full-text search over symbol names, docstrings, and signatures.
         *
         *     Reuses handle_seam_search which applies FTS5 + rescoring + LIKE/fuzzy fallback.
         *     Returns matching symbols with their file location, kind, and cluster info.
         */
        get: operations["get_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/neighborhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Neighborhood
         * @description Return a depth-1 neighborhood graph for a symbol.
         *
         *     Nodes = unique symbol NAMES (homonym-collapse, consistent with seam_impact/trace).
         *     Edges carry kind (call/import) and confidence (EXTRACTED/INFERRED/AMBIGUOUS).
         *     Unknown symbol returns empty nodes/edges (not a 404 — the client may be expanding
         *     a node whose declaration is outside the indexed files).
         */
        get: operations["get_neighborhood_api_graph_neighborhood_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbol/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol
         * @description Return full detail for a symbol name.
         *
         *     Returns ALL definitions (for homonyms), callers, callees, cluster info,
         *     peers, and WHY/HACK/NOTE/TODO/FIXME comments.
         *
         *     Reuses handle_seam_context (360-degree view) and handle_seam_why.
         *     404 with {"found": false} when the symbol is not in the index.
         */
        get: operations["get_symbol_api_symbol__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Clusters
         * @description Return all functional-area clusters in the index.
         *
         *     Each cluster has an id, label (deterministic or LLM-generated), and size
         *     (number of symbols). Returns an empty list when no clusters exist (e.g.
         *     fresh index with SEAM_CLUSTER_MIN_SIZE=2 and very few edges).
         */
        get: operations["get_clusters_api_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Impact
         * @description Blast-radius analysis for a symbol, grouped by risk tier.
         *
         *     Reuses handle_seam_impact verbatim. verbose=False keeps the payload lean
         *     (only name/distance/confidence/tier/file/is_test per entry). Unknown symbol
         *     returns found:false with empty tiers (not a 404 — same contract as the MCP tool).
         */
        get: operations["get_impact_api_impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace
         * @description Shortest call/dependency path from source to target.
         *
         *     Reuses handle_seam_trace; only `paths` is surfaced (verbose=False strips
         *     per-hop provenance). found:false + empty paths when unconnected.
         */
        get: operations["get_trace_api_trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Changes
         * @description Git diff → changed symbols → risk level.
         *
         *     Reuses handle_seam_changes. NOT_A_GIT_REPO (non-git root) is mapped to 400
         *     by _check_handler_error, which the SPA shows as a friendly notice.
         */
        get: operations["get_changes_api_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Constellation
         * @description Whole-repo overview: cluster regions + weighted inter-cluster links.
         *
         *     Reuses build_constellation (graph_api). Empty/pre-v4 index → empty envelope.
         */
        get: operations["get_constellation_api_constellation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hubs
         * @description Return the most-connected symbols — landing-page entry points.
         *
         *     Reuses graph_api.top_hub_symbols (degree-ranked, defined-only).
         *     show_tests=false (default) excludes test-path symbols (real hubs only).
         *     Pass show_tests=true to include test helpers in the hub list.
         */
        get: operations["get_hubs_api_hubs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Structure
         * @description Return every symbol with its file path — source for the structure treemap.
         *
         *     Reuses graph_api.list_structure; paths are relativized to the project root.
         *     The SPA builds the folder → file → class → method tree from this flat list.
         */
        get: operations["get_structure_api_structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AffectedEntry
         * @description A symbol impacted by the changed set (downstream of a change).
         */
        AffectedEntry: {
            /** Name */
            name: string;
            /** File */
            file: string | null;
            /** Tier */
            tier: string;
            /** Confidence */
            confidence: string;
            /** Distance */
            distance: number;
        };
        /**
         * ArchitectureCounts
         * @description Scoped and global population counts for GET /api/architecture.
         */
        ArchitectureCounts: {
            /** Files */
            files: number;
            /** Symbols */
            symbols: number;
            /** Edges */
            edges: number;
            /** Clusters */
            clusters: number;
            /** Comments */
            comments: number;
            /** Import Mappings */
            import_mappings: number;
            /** Embeddings */
            embeddings: number;
            /** Routes */
            routes: number;
            /** Http Calls */
            http_calls: number;
            /** Config Keys */
            config_keys: number;
            /** Resources */
            resources: number;
            /** Test Files */
            test_files: number;
            /** Production Files */
            production_files: number;
            /** Unknown Files */
            unknown_files: number;
        };
        /**
         * ArchitectureEdgeMixSection
         * @description Relationship-kind and confidence distribution.
         */
        ArchitectureEdgeMixSection: {
            /** Edge Kinds */
            edge_kinds: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: {
                [key: string]: number;
            };
            /** Synthesized */
            synthesized: {
                [key: string]: number;
            };
            /** Synthesized Total */
            synthesized_total: number;
        };
        /**
         * ArchitectureEvidenceSection
         * @description Bounded evidence section with status, count, and optional explanation.
         */
        ArchitectureEvidenceSection: {
            /** Status */
            status: string;
            /** Count */
            count: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Truncated */
            truncated: number;
            /** Reason */
            reason?: string | null;
        };
        /**
         * ArchitectureExceptionsSection
         * @description Exception-flow summary for explicit raises/throws and typed catches.
         */
        ArchitectureExceptionsSection: {
            /** Status */
            status: string;
            /** Raised Types */
            raised_types?: {
                [key: string]: unknown;
            }[] | null;
            /** Caught Types */
            caught_types?: {
                [key: string]: unknown;
            }[] | null;
            /** Broad Catches */
            broad_catches?: {
                [key: string]: unknown;
            }[] | null;
            /** Heavy Symbols */
            heavy_symbols?: {
                [key: string]: unknown;
            }[] | null;
            /** Truncated */
            truncated: number;
            /** Reason */
            reason?: string | null;
        };
        /**
         * ArchitectureFreshness
         * @description Index freshness block in GET /api/architecture.
         */
        ArchitectureFreshness: {
            /** Stale */
            stale: boolean;
            /** Reason */
            reason: string | null;
            /** Hint */
            hint: string | null;
        };
        /**
         * ArchitectureIdentity
         * @description Version identity for GET /api/architecture.
         */
        ArchitectureIdentity: {
            /** Schema Version */
            schema_version: number | string;
            /** Seam Version */
            seam_version: string;
            /** Index Seam Version */
            index_seam_version: string | null;
        };
        /**
         * ArchitectureListSection
         * @description Ranked section with bounded, schema-flexible item dictionaries.
         */
        ArchitectureListSection: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Truncated */
            truncated: number;
        };
        /**
         * ArchitectureNextCall
         * @description Recommended follow-up Seam call.
         */
        ArchitectureNextCall: {
            /** Tool */
            tool: string;
            /** Reason */
            reason: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /**
         * ArchitectureOptionalSurface
         * @description Status placeholder for config/resource/test-edge surfaces.
         */
        ArchitectureOptionalSurface: {
            /** Status */
            status: string;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Reason */
            reason?: string | null;
        };
        /**
         * ArchitecturePhysicalSection
         * @description Filesystem-oriented architecture section.
         */
        ArchitecturePhysicalSection: {
            /** Top Areas */
            top_areas: {
                [key: string]: unknown;
            }[];
            /** Structure */
            structure: {
                [key: string]: unknown;
            };
            /** Truncated */
            truncated: number;
        };
        /**
         * ArchitectureResponse
         * @description Response for GET /api/architecture.
         */
        ArchitectureResponse: {
            identity: components["schemas"]["ArchitectureIdentity"];
            freshness: components["schemas"]["ArchitectureFreshness"];
            scope: components["schemas"]["ArchitectureScope"];
            counts: components["schemas"]["ArchitectureCounts"];
            sections: components["schemas"]["ArchitectureSections"];
            /** Warnings */
            warnings: components["schemas"]["SchemaWarning"][];
            /** Truncation */
            truncation: {
                [key: string]: unknown;
            };
            /** Next Calls */
            next_calls: components["schemas"]["ArchitectureNextCall"][];
        };
        /**
         * ArchitectureScope
         * @description Scope application metadata for GET /api/architecture.
         */
        ArchitectureScope: {
            /** Path */
            path: string | null;
            /** Applied */
            applied: boolean;
        };
        /**
         * ArchitectureSections
         * @description Optional architecture sections selected by the caller.
         */
        ArchitectureSections: {
            summary?: components["schemas"]["ArchitectureSummarySection"] | null;
            languages?: components["schemas"]["ArchitectureListSection"] | null;
            physical?: components["schemas"]["ArchitecturePhysicalSection"] | null;
            clusters?: components["schemas"]["ArchitectureListSection"] | null;
            entry_points?: components["schemas"]["ArchitectureListSection"] | null;
            routes?: components["schemas"]["ArchitectureListSection"] | null;
            http_calls?: components["schemas"]["ArchitectureEvidenceSection"] | null;
            configs?: components["schemas"]["ArchitectureListSection"] | null;
            resources?: components["schemas"]["ArchitectureListSection"] | null;
            infra?: components["schemas"]["ArchitectureListSection"] | null;
            hotspots?: components["schemas"]["ArchitectureListSection"] | null;
            orchestrators?: components["schemas"]["ArchitectureListSection"] | null;
            boundaries?: components["schemas"]["ArchitectureListSection"] | null;
            edge_mix?: components["schemas"]["ArchitectureEdgeMixSection"] | null;
            exceptions?: components["schemas"]["ArchitectureExceptionsSection"] | null;
            tests?: components["schemas"]["ArchitectureTestsSection"] | null;
            /** Optional Surfaces */
            optional_surfaces?: {
                [key: string]: components["schemas"]["ArchitectureOptionalSurface"];
            } | null;
        };
        /**
         * ArchitectureSummarySection
         * @description Human-readable one-line summary.
         */
        ArchitectureSummarySection: {
            /** Text */
            text: string;
        };
        /**
         * ArchitectureTestsSection
         * @description Test/prod split and explicit coverage-edge status.
         */
        ArchitectureTestsSection: {
            /** Files */
            files: {
                [key: string]: number;
            };
            /** Coverage Edges */
            coverage_edges: {
                [key: string]: unknown;
            };
            /** Top Tested Symbols */
            top_tested_symbols?: {
                [key: string]: unknown;
            }[] | null;
            /** Test Heavy Sources */
            test_heavy_sources?: {
                [key: string]: unknown;
            }[] | null;
            /** Untested Hotspots */
            untested_hotspots?: {
                [key: string]: unknown;
            }[] | null;
            /** Truncated */
            truncated?: number | null;
        };
        /**
         * CallerRef
         * @description S2 enriched caller/callee: edge metadata added at the web layer.
         *
         *     The context handler returns bare name strings; fetch_edge_refs enriches them
         *     with kind + confidence from a direct edges query (no handler change).
         */
        CallerRef: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Confidence */
            confidence: string;
        };
        /**
         * ChangedSymbol
         * @description A symbol touched by the current diff.
         */
        ChangedSymbol: {
            /** Name */
            name: string;
            /** File */
            file: string | null;
            /** Kind */
            kind: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Changed Lines */
            changed_lines: number[];
        };
        /**
         * ChangesResponse
         * @description Response for GET /api/changes (git diff → changed symbols → risk).
         */
        ChangesResponse: {
            /** Changed Symbols */
            changed_symbols: components["schemas"]["ChangedSymbol"][];
            /** New Files */
            new_files: string[];
            /** Affected */
            affected: components["schemas"]["AffectedEntry"][];
            /** Risk Level */
            risk_level: string;
            /** Ambiguous Warning */
            ambiguous_warning: boolean;
            /** Scope */
            scope: string;
            /** Base Ref */
            base_ref: string;
            /** Partial */
            partial: boolean;
        };
        /**
         * ClusterInfo
         * @description Cluster identity for a symbol.
         */
        ClusterInfo: {
            /** Id */
            id: number;
            /** Label */
            label: string | null;
        };
        /**
         * ClusterItem
         * @description One cluster in the cluster list.
         *
         *     `representative` is a member symbol NAME the UI can center the graph on when
         *     the cluster is clicked — clusters aren't symbols, so the landing page needs a
         *     real symbol to open. None only if the cluster has no members (degrades safely).
         */
        ClusterItem: {
            /** Cluster Id */
            cluster_id: number;
            /** Label */
            label: string | null;
            /** Size */
            size: number;
            /** Representative */
            representative: string | null;
        };
        /**
         * ClustersResponse
         * @description Response for GET /api/clusters.
         */
        ClustersResponse: {
            /** Clusters */
            clusters: components["schemas"]["ClusterItem"][];
        };
        /**
         * ConstellationCluster
         * @description One cluster region in the whole-repo overview.
         *
         *     C1: `representative` is the MIN(id) member symbol name for this cluster —
         *     the same value /api/clusters returns (single source of truth). None only for
         *     orphan clusters that have no symbols assigned (rare in practice).
         */
        ConstellationCluster: {
            /** Cluster Id */
            cluster_id: number;
            /** Label */
            label: string | null;
            /** Size */
            size: number;
            /** Representative */
            representative?: string | null;
        };
        /**
         * ConstellationLink
         * @description A weighted inter-cluster link (count of cross-cluster edges).
         */
        ConstellationLink: {
            /** Source */
            source: number;
            /** Target */
            target: number;
            /** Weight */
            weight: number;
        };
        /**
         * ConstellationResponse
         * @description Response for GET /api/constellation.
         */
        ConstellationResponse: {
            /** Clusters */
            clusters: components["schemas"]["ConstellationCluster"][];
            /** Links */
            links: components["schemas"]["ConstellationLink"][];
        };
        /**
         * GraphEdge
         * @description An edge in the neighborhood graph.
         */
        GraphEdge: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Kind */
            kind: string;
            /** Confidence */
            confidence: string;
        };
        /**
         * GraphNode
         * @description A node in the neighborhood graph (one per unique symbol NAME).
         */
        GraphNode: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Signature */
            signature: string | null;
            /** Visibility */
            visibility: string | null;
            /** Is Exported */
            is_exported: boolean | null;
            /** Cluster Id */
            cluster_id: number | null;
            /** Cluster Label */
            cluster_label: string | null;
            /** Definition Count */
            definition_count: number;
        };
        /**
         * GraphSearchDegreeSummary
         * @description Incoming/outgoing/total relationship counts for a structural result.
         */
        GraphSearchDegreeSummary: {
            /** Incoming */
            incoming: number;
            /** Outgoing */
            outgoing: number;
            /** Total */
            total: number;
        };
        /**
         * GraphSearchItem
         * @description One structural graph-search hit, intentionally metadata-only.
         */
        GraphSearchItem: {
            /** Symbol */
            symbol: string;
            /** Uid */
            uid: string;
            /** Kind */
            kind: string;
            /** File */
            file: string;
            /** Line */
            line: number;
            /** End Line */
            end_line: number;
            /** Signature */
            signature: string | null;
            /** Qualified Name */
            qualified_name: string | null;
            /** Visibility */
            visibility: string | null;
            /** Is Exported */
            is_exported: boolean | null;
            /** Language */
            language: string | null;
            /** Cluster Id */
            cluster_id: number | null;
            /** Cluster Label */
            cluster_label: string | null;
            /** Is Test */
            is_test: boolean;
            degrees: components["schemas"]["GraphSearchDegreeSummary"];
            /** Preview */
            preview?: components["schemas"]["GraphSearchPreviewItem"][] | null;
            /** Preview Truncated */
            preview_truncated?: boolean | null;
        };
        /**
         * GraphSearchPreviewItem
         * @description One bounded connected-node preview entry.
         */
        GraphSearchPreviewItem: {
            /** Direction */
            direction: string;
            /** Symbol */
            symbol: string;
            /** Uid */
            uid: string | null;
            /** Kind */
            kind: string | null;
            /** File */
            file: string;
            /** Line */
            line: number;
            /** Edge Kind */
            edge_kind: string;
            /** Confidence */
            confidence: string;
            /** Receiver */
            receiver?: string | null;
            /** Synthesized By */
            synthesized_by?: string | null;
            /** Provenance */
            provenance?: string | null;
            /** Route Resolved */
            route_resolved?: boolean | null;
        };
        /**
         * GraphSearchResponse
         * @description Response for GET /api/graph/search.
         */
        GraphSearchResponse: {
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Items */
            items: components["schemas"]["GraphSearchItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
            /** Warnings */
            warnings: components["schemas"]["SchemaWarning"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HubSymbol
         * @description A highest-degree 'hub' symbol — a landing-page entry point.
         */
        HubSymbol: {
            /** Name */
            name: string;
            /** Kind */
            kind: string | null;
            /** Degree */
            degree: number;
            /** Path */
            path: string | null;
        };
        /**
         * HubsResponse
         * @description Response for GET /api/hubs.
         */
        HubsResponse: {
            /** Symbols */
            symbols: components["schemas"]["HubSymbol"][];
        };
        /**
         * ImpactEntry
         * @description One affected symbol in an impact (blast-radius) result.
         *
         *     Lean field set: identity + tier + location. Heavy provenance fields
         *     (resolved_by/best_candidate) are stripped via verbose=False.
         *     S2: 'kind' added — edge kind of the final hop; present when SEAM_EDGE_PROVENANCE=on.
         *     'kind' is a core handler field (NOT in _HEAVY_FIELDS) that survived verbose=False
         *     but was discarded by Pydantic until this model declared it.
         */
        ImpactEntry: {
            /** Name */
            name: string;
            /** Distance */
            distance: number;
            /** Confidence */
            confidence: string;
            /** Tier */
            tier: string;
            /** File */
            file: string | null;
            /** Is Test */
            is_test: boolean;
            /** Kind */
            kind?: string | null;
        };
        /**
         * ImpactResponse
         * @description Response for GET /api/impact.
         *
         *     risk_summary reflects honest full-count per tier (pre-cap). upstream/downstream
         *     present only for the requested direction(s). truncated present only when capped.
         */
        ImpactResponse: {
            /** Found */
            found: boolean;
            /** Target */
            target: string;
            /** Risk Summary */
            risk_summary: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Upstream */
            upstream?: {
                [key: string]: components["schemas"]["ImpactEntry"][];
            } | null;
            /** Downstream */
            downstream?: {
                [key: string]: components["schemas"]["ImpactEntry"][];
            } | null;
            /** Truncated */
            truncated?: {
                [key: string]: {
                    [key: string]: number;
                };
            } | null;
        };
        /**
         * LayoutClusterModel
         * @description Functional-area cluster summary for halo rendering.
         */
        LayoutClusterModel: {
            /** Cluster Id */
            cluster_id: number;
            /** Label */
            label: string | null;
            /** Centroid */
            centroid: number[];
            /** Radius */
            radius: number;
            /** Color */
            color: string;
        };
        /**
         * LayoutEdgeModel
         * @description One directed edge between layout nodes, referenced by node id.
         */
        LayoutEdgeModel: {
            /** Source */
            source: number;
            /** Target */
            target: number;
            /** Type */
            type: string;
        };
        /**
         * LayoutNodeModel
         * @description One positioned node in the constellation layout.
         */
        LayoutNodeModel: {
            /** Id */
            id: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** File Path */
            file_path: string | null;
            /** Size */
            size: number;
            /** Color */
            color: string;
        };
        /**
         * LayoutResponse
         * @description Response body for GET /api/graph/layout.
         */
        LayoutResponse: {
            /** Nodes */
            nodes: components["schemas"]["LayoutNodeModel"][];
            /** Edges */
            edges: components["schemas"]["LayoutEdgeModel"][];
            /** Clusters */
            clusters: components["schemas"]["LayoutClusterModel"][];
            /** Total Nodes */
            total_nodes: number;
        };
        /**
         * NeighborhoodResponse
         * @description Response for GET /api/graph/neighborhood.
         */
        NeighborhoodResponse: {
            /** Center */
            center: string;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /**
         * SchemaBreakdowns
         * @description Small grouped-count maps for GET /api/schema.
         */
        SchemaBreakdowns: {
            /** Languages */
            languages: {
                [key: string]: number;
            };
            /** Symbol Kinds */
            symbol_kinds: {
                [key: string]: number;
            };
            /** Edge Kinds */
            edge_kinds: {
                [key: string]: number;
            };
            /** Edge Confidence */
            edge_confidence: {
                [key: string]: number;
            };
            /** Synthesized Edges */
            synthesized_edges: {
                [key: string]: number;
            };
            /** Comment Markers */
            comment_markers: {
                [key: string]: number;
            };
            /** Embedding Models */
            embedding_models: {
                [key: string]: number;
            };
            /** Resource Categories */
            resource_categories: {
                [key: string]: number;
            };
        };
        /**
         * SchemaCapabilities
         * @description Derived feature booleans for GET /api/schema.
         */
        SchemaCapabilities: {
            /** Has Clusters */
            has_clusters: boolean;
            /** Has Comments */
            has_comments: boolean;
            /** Has Import Mappings */
            has_import_mappings: boolean;
            /** Has Embeddings */
            has_embeddings: boolean;
            /** Embedding Model Matches */
            embedding_model_matches: boolean;
            /** Has Synthesized Edges */
            has_synthesized_edges: boolean;
            /** Has Field Symbols */
            has_field_symbols: boolean;
            /** Has Receiver Column */
            has_receiver_column: boolean;
            /** Has Search Text */
            has_search_text: boolean;
            /** Has Signature Column */
            has_signature_column: boolean;
            /** Has Synthesized By Column */
            has_synthesized_by_column: boolean;
            /** Has Edge Provenance Column */
            has_edge_provenance_column: boolean;
            /** Has Routes Table */
            has_routes_table: boolean;
            /** Has Route Nodes */
            has_route_nodes: boolean;
            /** Has Http Calls */
            has_http_calls: boolean;
            /** Has Config Keys Table */
            has_config_keys_table: boolean;
            /** Has Resources Table */
            has_resources_table: boolean;
            /** Has Config Nodes */
            has_config_nodes: boolean;
            /** Has Resource Nodes */
            has_resource_nodes: boolean;
            /** Has Infra Graph */
            has_infra_graph: boolean;
            /** Has Reads Config */
            has_reads_config: boolean;
            /** Has Configures */
            has_configures: boolean;
            /** Has Exception Edges */
            has_exception_edges: boolean;
            /** Has Test Edges */
            has_test_edges: boolean;
        };
        /**
         * SchemaColumnInfo
         * @description Verbose column metadata for GET /api/schema?verbose=true.
         */
        SchemaColumnInfo: {
            /** Exists */
            exists: boolean;
            /** Type */
            type: string | null;
            /** Notnull */
            notnull: boolean;
            /** Default */
            default: unknown;
            /** Primary Key */
            primary_key: boolean;
        };
        /**
         * SchemaCounts
         * @description Top-level index population counts in GET /api/schema.
         */
        SchemaCounts: {
            /** Files */
            files: number;
            /** Symbols */
            symbols: number;
            /** Edges */
            edges: number;
            /** Clusters */
            clusters: number;
            /** Comments */
            comments: number;
            /** Import Mappings */
            import_mappings: number;
            /** Embeddings */
            embeddings: number;
            /** Routes */
            routes: number;
            /** Http Calls */
            http_calls: number;
            /** Config Keys */
            config_keys: number;
            /** Resources */
            resources: number;
        };
        /**
         * SchemaFreshness
         * @description Index freshness block in GET /api/schema.
         */
        SchemaFreshness: {
            /** Stale */
            stale: boolean;
            /** Reason */
            reason: string | null;
            /** Hint */
            hint: string | null;
        };
        /**
         * SchemaResponse
         * @description Response for GET /api/schema.
         */
        SchemaResponse: {
            /** Schema Version */
            schema_version: number | string;
            /** Seam Version */
            seam_version: string;
            /** Index Seam Version */
            index_seam_version: string | null;
            freshness: components["schemas"]["SchemaFreshness"];
            counts: components["schemas"]["SchemaCounts"];
            breakdowns: components["schemas"]["SchemaBreakdowns"];
            capabilities: components["schemas"]["SchemaCapabilities"];
            /** Tools */
            tools: components["schemas"]["SchemaToolGuide"][];
            /** Recommended Next Calls */
            recommended_next_calls: string[];
            /** Warnings */
            warnings: components["schemas"]["SchemaWarning"][];
            /** Tables */
            tables?: {
                [key: string]: components["schemas"]["SchemaTableInfo"];
            } | null;
        };
        /**
         * SchemaTableInfo
         * @description Verbose table metadata for GET /api/schema?verbose=true.
         */
        SchemaTableInfo: {
            /** Exists */
            exists: boolean;
            /** Columns */
            columns: {
                [key: string]: components["schemas"]["SchemaColumnInfo"];
            };
        };
        /**
         * SchemaToolGuide
         * @description One tool-guidance entry in GET /api/schema.
         */
        SchemaToolGuide: {
            /** Name */
            name: string;
            /** Transports */
            transports: string[];
            /** Read Only */
            read_only: boolean;
            /** Use When */
            use_when: string;
            /** Depends On */
            depends_on?: string[] | null;
        };
        /**
         * SchemaWarning
         * @description Structured warning emitted by GET /api/schema.
         */
        SchemaWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Hint */
            hint: string;
        };
        /**
         * SearchResponse
         * @description Response for GET /api/search.
         */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
        };
        /**
         * SearchResultItem
         * @description One item in a search result list.
         */
        SearchResultItem: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** File */
            file: string;
            /** Line */
            line: number;
            /** Signature */
            signature: string | null;
            /** Cluster Id */
            cluster_id: number | null;
            /** Cluster Label */
            cluster_label: string | null;
        };
        /**
         * SnippetCandidate
         * @description Candidate selector returned instead of guessing when a source lookup is ambiguous.
         */
        SnippetCandidate: {
            /** Symbol */
            symbol: string;
            /** Uid */
            uid: string;
            /** Kind */
            kind: string;
            /** File */
            file: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Signature */
            signature: string | null;
        };
        /**
         * SnippetFreshness
         * @description Freshness signals protect callers from trusting line ranges after local edits.
         */
        SnippetFreshness: {
            /** File Hash Matches */
            file_hash_matches: boolean;
            /** Mtime Matches */
            mtime_matches: boolean;
            /** Index Stale */
            index_stale: boolean;
        };
        /**
         * SnippetResponse
         * @description Typed union-style payload because not-found and ambiguity are successful reads.
         */
        SnippetResponse: {
            /** Found */
            found: boolean;
            /** Symbol */
            symbol?: string | null;
            /** Uid */
            uid?: string | null;
            /** Kind */
            kind?: string | null;
            /** File */
            file?: string | null;
            /** Start Line */
            start_line?: number | null;
            /** End Line */
            end_line?: number | null;
            /** Source Start Line */
            source_start_line?: number | null;
            /** Source End Line */
            source_end_line?: number | null;
            /** Signature */
            signature?: string | null;
            /** Docstring */
            docstring?: string | null;
            /** Source */
            source?: string | null;
            truncated?: components["schemas"]["SnippetTruncation"] | null;
            freshness?: components["schemas"]["SnippetFreshness"] | null;
            /** Neighbors */
            neighbors?: components["schemas"]["SnippetCandidate"][] | null;
            /** Ambiguous */
            ambiguous?: boolean | null;
            /** Reason */
            reason?: string | null;
            /** Message */
            message?: string | null;
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["SnippetCandidate"][];
            /** Warnings */
            warnings: components["schemas"]["SnippetWarning"][];
        };
        /**
         * SnippetTruncation
         * @description Truncation metadata preserves the difference between a small symbol and a capped read.
         */
        SnippetTruncation: {
            /** By Lines */
            by_lines: boolean;
            /** By Bytes */
            by_bytes: boolean;
            /** Original Line Count */
            original_line_count: number;
            /** Returned Line Count */
            returned_line_count: number;
        };
        /**
         * SnippetWarning
         * @description Machine-readable warning so UI callers can route stale/truncated reads distinctly.
         */
        SnippetWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Hint */
            hint: string;
        };
        /**
         * StatusResponse
         * @description Response for GET /api/status.
         *
         *     stale + stale_reason are ADDITIVE fields added in #272.
         *     They mirror the same check_staleness() call used by the MCP graph-traversal
         *     handlers so /api/status can never disagree with `seam status`.
         *     stale_reason is None when the index is fresh.
         */
        StatusResponse: {
            /** Root */
            root: string;
            /** Symbol Count */
            symbol_count: number;
            /** Edge Count */
            edge_count: number;
            /** Cluster Count */
            cluster_count: number;
            /** Last Indexed */
            last_indexed: string | null;
            /** Languages */
            languages: string[];
            /** Stale */
            stale: boolean;
            /** Stale Reason */
            stale_reason: string | null;
        };
        /**
         * StructureResponse
         * @description Response for GET /api/structure.
         */
        StructureResponse: {
            /** Symbols */
            symbols: components["schemas"]["StructureSymbol"][];
        };
        /**
         * StructureSymbol
         * @description One symbol row for the structure map (flat — the SPA builds the tree).
         *
         *     B2: `degree` = fan-in / incoming edge count (edges pointing TO this symbol).
         *     Computed at read time via an additive LEFT JOIN — no schema change, no re-index.
         *     Zero when a symbol has no incoming edges (isolated or outgoing-only).
         */
        StructureSymbol: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Line */
            line: number;
            /** Qualified Name */
            qualified_name: string | null;
            /** Degree */
            degree: number;
        };
        /**
         * SymbolDefinition
         * @description One definition (file-level occurrence) of a symbol.
         */
        SymbolDefinition: {
            /** File */
            file: string;
            /** Line */
            line: number;
            /** Signature */
            signature: string | null;
            /** Docstring */
            docstring: string | null;
            /** Visibility */
            visibility: string | null;
            /** Is Exported */
            is_exported: boolean | null;
            /** Qualified Name */
            qualified_name: string | null;
            /** Decorators */
            decorators: string[];
        };
        /**
         * SymbolResponse
         * @description Response for GET /api/symbol/{name}.
         */
        SymbolResponse: {
            /** Name */
            name: string;
            /** Definitions */
            definitions: components["schemas"]["SymbolDefinition"][];
            /** Callers */
            callers: components["schemas"]["CallerRef"][];
            /** Callees */
            callees: components["schemas"]["CallerRef"][];
            cluster: components["schemas"]["ClusterInfo"] | null;
            /** Peers */
            peers: string[];
            /** Why */
            why: components["schemas"]["WhyComment"][];
        };
        /**
         * TraceHop
         * @description One edge in a trace path.
         */
        TraceHop: {
            /** From Name */
            from_name: string;
            /** To Name */
            to_name: string;
            /** Kind */
            kind: string;
            /** Confidence */
            confidence: string;
        };
        /**
         * TraceResponse
         * @description Response for GET /api/trace.
         *
         *     Only `paths` is surfaced (the path overlay's input). The handler's neighbor lists
         *     are dropped — the neighborhood endpoint covers those. paths[0] is the shortest path;
         *     empty list when source and target are not connected.
         */
        TraceResponse: {
            /** Found */
            found: boolean;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Paths */
            paths: components["schemas"]["TraceHop"][][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WhyComment
         * @description A WHY/HACK/NOTE/TODO/FIXME comment near a symbol.
         */
        WhyComment: {
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** File */
            file: string;
            /** Line */
            line: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_graph_search_api_graph_search_get: {
        parameters: {
            query?: {
                /** @description Symbol kind filter. */
                kind?: string | null;
                /** @description Symbol name glob or regex. */
                name_pattern?: string | null;
                /** @description Qualified-name glob/regex. */
                qualified_name_pattern?: string | null;
                /** @description Root-relative file glob/regex. */
                file_pattern?: string | null;
                /** @description Indexed language filter. */
                language?: string | null;
                /** @description Edge kind or comma-separated edge kinds. */
                edge_kind?: string | null;
                /** @description incoming | outgoing | both */
                direction?: string;
                min_degree?: number | null;
                max_degree?: number | null;
                min_in_degree?: number | null;
                max_in_degree?: number | null;
                min_out_degree?: number | null;
                max_out_degree?: number | null;
                /** @description EXTRACTED | INFERRED | AMBIGUOUS */
                confidence?: string | null;
                /** @description any | parser | synthesized */
                synthesized?: string;
                cluster_id?: number | null;
                visibility?: string | null;
                is_exported?: boolean | null;
                /** @description any | test | source */
                test_scope?: string;
                /** @description dead-code | hotspot | field-access | inheritance | isolates */
                preset?: string | null;
                /** @description default | in-degree | out-degree | total-degree | name | file | line */
                sort?: string;
                limit?: number;
                offset?: number;
                include_preview?: boolean;
                preview_limit?: number;
                regex?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_architecture_api_architecture_get: {
        parameters: {
            query?: {
                /** @description Root-relative path to summarize. */
                scope?: string | null;
                /** @description Architecture section to include; repeatable. */
                section?: string[] | null;
                limit?: number;
                max_bytes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchitectureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layout_api_graph_layout_get: {
        parameters: {
            query?: {
                /** @description Maximum number of nodes to include in the layout. Nodes are selected by degree DESC (most-connected first). total_nodes in the response reflects the true count before this cap. */
                max_nodes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_schema_get: {
        parameters: {
            query?: {
                /** @description Include verbose table and column metadata for diagnostics. */
                verbose?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snippet_api_snippet_get: {
        parameters: {
            query?: {
                /** @description Exact symbol UID from search/query. */
                uid?: string | null;
                /** @description Symbol name to retrieve. */
                symbol?: string | null;
                /** @description Root-relative or absolute file path. */
                file?: string | null;
                /** @description 1-based source line. */
                line?: number | null;
                /** @description Context lines around symbol. */
                context_lines?: number;
                /** @description Maximum source lines. */
                max_lines?: number;
                /** @description Maximum UTF-8 bytes. */
                max_bytes?: number;
                /** @description Include previous/next indexed symbols from the same file. */
                include_neighbors?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnippetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_search_api_search_get: {
        parameters: {
            query: {
                /** @description Search query text */
                q: string;
                /** @description Maximum results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neighborhood_api_graph_neighborhood_get: {
        parameters: {
            query: {
                /** @description Symbol name to center the graph on */
                symbol: string;
                /** @description Edge direction: 'both' | 'callers' | 'callees' */
                direction?: "both" | "callers" | "callees";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_symbol_api_symbol__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolResponse"];
                };
            };
            /** @description Symbol not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clusters_api_clusters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClustersResponse"];
                };
            };
        };
    };
    get_impact_api_impact_get: {
        parameters: {
            query: {
                /** @description Target symbol to analyze */
                symbol: string;
                /** @description Blast-radius direction */
                direction?: "both" | "upstream" | "downstream";
                /** @description Max traversal hops */
                max_depth?: number;
                /** @description Include test-file dependents */
                include_tests?: boolean;
                /** @description Per-tier cap (0 = unlimited) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_trace_get: {
        parameters: {
            query: {
                /** @description Path start symbol */
                source: string;
                /** @description Path end symbol */
                target: string;
                /** @description Max path length in hops */
                max_depth?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_changes_api_changes_get: {
        parameters: {
            query?: {
                /** @description Diff scope */
                scope?: "working" | "staged" | "branch";
                /** @description Base ref (branch scope only) */
                base_ref?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_constellation_api_constellation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstellationResponse"];
                };
            };
        };
    };
    get_hubs_api_hubs_get: {
        parameters: {
            query?: {
                /** @description How many hub symbols to return */
                limit?: number;
                /** @description Include symbols from test paths (default: false) */
                show_tests?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_structure_api_structure_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
        };
    };
}
