/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Return index statistics and metadata.
         *
         *     Returns symbol_count, edge_count, cluster_count, last_indexed timestamp,
         *     and the list of languages present in the index.
         */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search
         * @description Full-text search over symbol names, docstrings, and signatures.
         *
         *     Reuses handle_seam_search which applies FTS5 + rescoring + LIKE/fuzzy fallback.
         *     Returns matching symbols with their file location, kind, and cluster info.
         */
        get: operations["get_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/neighborhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Neighborhood
         * @description Return a depth-1 neighborhood graph for a symbol.
         *
         *     Nodes = unique symbol NAMES (homonym-collapse, consistent with seam_impact/trace).
         *     Edges carry kind (call/import) and confidence (EXTRACTED/INFERRED/AMBIGUOUS).
         *     Unknown symbol returns empty nodes/edges (not a 404 — the client may be expanding
         *     a node whose declaration is outside the indexed files).
         */
        get: operations["get_neighborhood_api_graph_neighborhood_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbol/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbol
         * @description Return full detail for a symbol name.
         *
         *     Returns ALL definitions (for homonyms), callers, callees, cluster info,
         *     peers, and WHY/HACK/NOTE/TODO/FIXME comments.
         *
         *     Reuses handle_seam_context (360-degree view) and handle_seam_why.
         *     404 with {"found": false} when the symbol is not in the index.
         */
        get: operations["get_symbol_api_symbol__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Clusters
         * @description Return all functional-area clusters in the index.
         *
         *     Each cluster has an id, label (deterministic or LLM-generated), and size
         *     (number of symbols). Returns an empty list when no clusters exist (e.g.
         *     fresh index with SEAM_CLUSTER_MIN_SIZE=2 and very few edges).
         */
        get: operations["get_clusters_api_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClusterInfo
         * @description Cluster identity for a symbol.
         */
        ClusterInfo: {
            /** Id */
            id: number;
            /** Label */
            label: string | null;
        };
        /**
         * ClusterItem
         * @description One cluster in the cluster list.
         *
         *     `representative` is a member symbol NAME the UI can center the graph on when
         *     the cluster is clicked as an entry point — clusters themselves are not symbols,
         *     so the landing page needs a real symbol to open. None only if the cluster has
         *     no clustered symbols (shouldn't happen, but degrades safely to label fallback).
         */
        ClusterItem: {
            /** Cluster Id */
            cluster_id: number;
            /** Label */
            label: string | null;
            /** Size */
            size: number;
            /** Representative */
            representative: string | null;
        };
        /**
         * ClustersResponse
         * @description Response for GET /api/clusters.
         */
        ClustersResponse: {
            /** Clusters */
            clusters: components["schemas"]["ClusterItem"][];
        };
        /**
         * GraphEdge
         * @description An edge in the neighborhood graph.
         */
        GraphEdge: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Kind */
            kind: string;
            /** Confidence */
            confidence: string;
        };
        /**
         * GraphNode
         * @description A node in the neighborhood graph (one per unique symbol NAME).
         */
        GraphNode: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Signature */
            signature: string | null;
            /** Visibility */
            visibility: string | null;
            /** Is Exported */
            is_exported: boolean | null;
            /** Cluster Id */
            cluster_id: number | null;
            /** Cluster Label */
            cluster_label: string | null;
            /** Definition Count */
            definition_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NeighborhoodResponse
         * @description Response for GET /api/graph/neighborhood.
         */
        NeighborhoodResponse: {
            /** Center */
            center: string;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /**
         * SearchResponse
         * @description Response for GET /api/search.
         */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
        };
        /**
         * SearchResultItem
         * @description One item in a search result list.
         */
        SearchResultItem: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** File */
            file: string;
            /** Line */
            line: number;
            /** Signature */
            signature: string | null;
            /** Cluster Id */
            cluster_id: number | null;
            /** Cluster Label */
            cluster_label: string | null;
        };
        /**
         * StatusResponse
         * @description Response for GET /api/status.
         */
        StatusResponse: {
            /** Root */
            root: string;
            /** Symbol Count */
            symbol_count: number;
            /** Edge Count */
            edge_count: number;
            /** Cluster Count */
            cluster_count: number;
            /** Last Indexed */
            last_indexed: string | null;
            /** Languages */
            languages: string[];
        };
        /**
         * SymbolDefinition
         * @description One definition (file-level occurrence) of a symbol.
         */
        SymbolDefinition: {
            /** File */
            file: string;
            /** Line */
            line: number;
            /** Signature */
            signature: string | null;
            /** Docstring */
            docstring: string | null;
            /** Visibility */
            visibility: string | null;
            /** Is Exported */
            is_exported: boolean | null;
            /** Qualified Name */
            qualified_name: string | null;
            /** Decorators */
            decorators: string[];
        };
        /**
         * SymbolResponse
         * @description Response for GET /api/symbol/{name}.
         */
        SymbolResponse: {
            /** Name */
            name: string;
            /** Definitions */
            definitions: components["schemas"]["SymbolDefinition"][];
            /** Callers */
            callers: string[];
            /** Callees */
            callees: string[];
            cluster: components["schemas"]["ClusterInfo"] | null;
            /** Peers */
            peers: string[];
            /** Why */
            why: components["schemas"]["WhyComment"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WhyComment
         * @description A WHY/HACK/NOTE/TODO/FIXME comment near a symbol.
         */
        WhyComment: {
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** File */
            file: string;
            /** Line */
            line: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_search_api_search_get: {
        parameters: {
            query: {
                /** @description Search query text */
                q: string;
                /** @description Maximum results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neighborhood_api_graph_neighborhood_get: {
        parameters: {
            query: {
                /** @description Symbol name to center the graph on */
                symbol: string;
                /** @description Edge direction: 'both' | 'callers' | 'callees' */
                direction?: "both" | "callers" | "callees";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_symbol_api_symbol__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolResponse"];
                };
            };
            /** @description Symbol not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clusters_api_clusters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClustersResponse"];
                };
            };
        };
    };
}
