"""File-as-context escape hatch for heavy Seam CLI read commands.

WHY this module exists (issue #226 / WS5 Slice 1):
  When a CLI command produces a large result (e.g. seam impact on a hub symbol),
  writing it inline to stdout burns the agent's entire context-window token budget.
  The --to-file escape hatch lets the agent land the full result on disk and read
  only the slice it cares about — measured at -46.9% agent tokens on similar tools.

Public responsibilities:
  1. summarize(data, command) -> str
       Pure, never raises. Returns a one-line human/agent summary of a command's
       result dict. Shape-aware per command; degrades to a generic message on any
       unexpected shape. Appends a short stale note when index_status is present.

  2. write_output_file(data, *, command, label, out_dir, path_override) -> ToFileResult
       Sanitizes the label, ensures the output directory exists, writes the compact
       JSON atomically (temp file + os.replace), and returns a ToFileResult with the
       resolved path, byte size, and the summary string.
       A genuine filesystem failure is surfaced to the caller (never silently swallowed).

Design constraints:
  - No new config knob: the --to-file CLI flag alone gates all new behavior.
  - Serializer matches seam/cli/output.py: json.dumps(data, ensure_ascii=False)
    so on-disk bytes match what the command would print in-band.
  - Import discipline: only stdlib + seam.cli.file_sink itself (leaf module).
"""

import json
import logging
import os
import re
import tempfile
from pathlib import Path
from typing import Any, TypedDict

logger = logging.getLogger(__name__)

# ── Result type ───────────────────────────────────────────────────────────────

# Maximum length for the sanitized label portion of the filename.
# Keeps the full filename well under the 255-char FS limit even with long symbol names.
_MAX_LABEL_LEN: int = 120

# Characters that are unsafe in filenames across common operating systems.
# Includes path separators (/ \), Windows-reserved chars, and dots (which would
# create confusing double-extensions like .py.json or enable relative-path tricks).
_UNSAFE_LABEL_RE: re.Pattern[str] = re.compile(r'[/\\:*?"<>|.\s]+')


class ToFileResult(TypedDict):
    """Result returned by write_output_file().

    Kept minimal: path (where the file was written), bytes (file size on disk),
    and summary (the one-line human/agent summary generated by summarize()).
    """

    path: Path
    bytes: int
    summary: str


# ── summarize() ───────────────────────────────────────────────────────────────


def summarize(data: Any, command: str) -> str:
    """Return a one-line summary of a command result dict.

    WHY pure and never-raises:
      This function is called on the --to-file path, which is a safety net for
      large results. Any exception here would crash the escape hatch precisely
      when the agent needs it most. The try/except fallback is intentional.

    WHY shape-aware per command rather than generic:
      The summary is the only thing printed to stdout when --to-file is active.
      An agent must be able to decide whether to open the file at all from this
      line alone. A generic "wrote output" provides no signal.

    Args:
        data:    The command's result dict (or any value — must never raise).
        command: The command name ("impact", "context", "trace", "flows", ...).

    Returns:
        A non-empty string. Appends " (index stale)" when the result carries an
        index_status banner with stale=True.
    """
    try:
        summary = _dispatch_summarize(data, command)
    except Exception:  # noqa: BLE001 — intentional safety net
        logger.debug("summarize() fallback triggered for command=%r", command, exc_info=True)
        summary = f"wrote {command} output"

    # Append staleness note when the result carries an index_status banner.
    # WHY check data isinstance dict: any non-dict degrades to generic above,
    # but we still need to guard here because _dispatch_summarize may have
    # succeeded even for non-standard shapes.
    try:
        if isinstance(data, dict):
            status = data.get("index_status")
            if isinstance(status, dict) and status.get("stale"):
                summary = summary + " (index stale)"
    except Exception:  # noqa: BLE001
        pass  # Never let the stale check crash the summary

    return summary


def _dispatch_summarize(data: Any, command: str) -> str:
    """Dispatch to the per-command summarizer.

    Raises on unexpected data shape so the caller's try/except can degrade
    to the generic message. This is the ONLY place exceptions are allowed.
    """
    if not isinstance(data, dict):
        raise TypeError(f"expected dict, got {type(data).__name__}")

    if command == "impact":
        return _summarize_impact(data)
    if command == "context":
        return _summarize_context(data)
    if command == "trace":
        return _summarize_trace(data)
    if command == "flows":
        return _summarize_flows(data)

    # Unknown command — fall through to generic
    raise ValueError(f"unknown command: {command!r}")


def _summarize_impact(data: dict[str, Any]) -> str:
    """Summarize a seam_impact result.

    Format: "<total> dependents (<direction>: WILL_BREAK=N, LIKELY_AFFECTED=N, MAY_NEED_TESTING=N)"

    WHY use risk_summary not the entry lists:
      risk_summary reflects the FULL pre-cap count (guaranteed by the handler);
      the entry lists may be truncated by --limit or --max-bytes. The summary
      should represent the honest blast radius, not just the shown slice.
    """
    risk: dict[str, Any] = data.get("risk_summary", {})
    if not isinstance(risk, dict) or not risk:
        # risk_summary absent or empty — probably a not-found result
        total = 0
        return f"{total} dependents"

    # Compute total and per-direction per-tier strings
    total = 0
    dir_parts: list[str] = []
    for direction in ("upstream", "downstream"):
        tier_group = risk.get(direction)
        if not isinstance(tier_group, dict):
            continue
        dir_total = sum(v for v in tier_group.values() if isinstance(v, int))
        total += dir_total
        tier_str = ", ".join(
            f"{t}={tier_group.get(t, 0)}"
            for t in ("WILL_BREAK", "LIKELY_AFFECTED", "MAY_NEED_TESTING")
            if t in tier_group
        )
        dir_parts.append(f"{direction}: {tier_str}")

    direction_label = "; ".join(dir_parts)
    return f"{total} dependents ({direction_label})"


def _summarize_context(data: dict[str, Any]) -> str:
    """Summarize a seam_context result.

    Format: "<N> callers, <M> callees" with "[ambiguous]" appended when set.
    """
    callers = data.get("callers", [])
    callees = data.get("callees", [])
    # Count safely — callers/callees should be lists but guard anyway
    n_callers = len(callers) if isinstance(callers, list) else 0
    n_callees = len(callees) if isinstance(callees, list) else 0
    ambiguous = bool(data.get("ambiguous"))

    summary = f"{n_callers} callers, {n_callees} callees"
    if ambiguous:
        summary += " [ambiguous]"
    return summary


def _summarize_trace(data: dict[str, Any]) -> str:
    """Summarize a seam_trace result.

    Format: "path found: N hops" or "no path".

    WHY use the first path's length as hop count:
      The trace result may contain multiple paths (different routes between the
      same pair of symbols). The first path is the shortest (the handler returns
      paths ordered by length). Using its length gives the most useful signal.
    """
    if not data.get("found"):
        return "no path"

    paths = data.get("paths", [])
    if not isinstance(paths, list) or not paths:
        return "path found: 0 hops"

    first_path = paths[0]
    n_hops = len(first_path) if isinstance(first_path, list) else 0
    return f"path found: {n_hops} hops"


def _summarize_flows(data: dict[str, Any]) -> str:
    """Summarize a seam_flows result.

    Three modes:
      - List mode (data has "entry_points"): "<N> entry points"
      - Expand mode (data has "steps"): "<N> steps, depth <D>"
      - Not found (data has found=False): "not found"
    """
    # Not-found case (from MCP boundary normalization or explicit wiring)
    if data.get("found") is False and "entry_points" not in data and "steps" not in data:
        return "not found"

    # List mode
    if "entry_points" in data:
        points = data["entry_points"]
        count = len(points) if isinstance(points, list) else 0
        return f"{count} entry points"

    # Expand mode
    if "steps" in data:
        total = data.get("total_steps", 0)
        depth = _max_depth(data.get("steps", []))
        return f"{total} steps, depth {depth}"

    # Unexpected shape — fall through to caller's fallback
    raise ValueError("unrecognized flows result shape")


def _max_depth(steps: Any, current_depth: int = 1) -> int:
    """Recursively compute the maximum depth of a FlowStep tree.

    WHY recursive not iterative:
      The tree is bounded by SEAM_FLOW_MAX_DEPTH (default 6) so recursion depth
      is always small and the code is clearer.

    Args:
        steps:         A list of FlowStep dicts (each has a "children" key).
        current_depth: Depth of the current level (entry = 0, direct steps = 1).

    Returns:
        Maximum depth reached in the tree. 0 when steps is empty.
    """
    if not isinstance(steps, list) or not steps:
        return 0

    max_d = current_depth
    for step in steps:
        children = step.get("children", []) if isinstance(step, dict) else []
        child_depth = _max_depth(children, current_depth + 1)
        if child_depth > max_d:
            max_d = child_depth
    return max_d


# ── write_output_file() ───────────────────────────────────────────────────────


def write_output_file(
    data: Any,
    *,
    command: str,
    label: str,
    out_dir: Path,
    path_override: Path | None = None,
) -> ToFileResult:
    """Write a command result to a JSON file and return a ToFileResult.

    WHY atomic write (temp file + os.replace):
      A concurrent agent reader could observe a partially written file if we
      wrote directly to the target path. The temp file is in the SAME directory
      so os.replace is always within the same filesystem (no cross-device error).

    WHY summarize() is called here:
      The summary must reflect the data actually written to disk. Generating it
      here prevents any drift between the on-disk content and the printed summary.

    Args:
        data:          The command's result dict. Must be JSON-serializable.
        command:       The command name (used for the auto filename and summary).
        label:         The symbol/label (used for the auto filename).
        out_dir:       The default output directory (.seam/out/ from the caller).
        path_override: Optional explicit path. If it is (or resolves to) a directory
                       the auto-named file is written inside it; otherwise it is
                       treated as the exact target file path.

    Returns:
        ToFileResult with path (Path to the written file), bytes (file size),
        and summary (the one-line summarize() result for this data).

    Raises:
        OSError / PermissionError: when the filesystem rejects the write.
          Never silently swallowed — the caller must surface this as an error envelope.
    """
    target_path = _resolve_target_path(command, label, out_dir, path_override)

    # Ensure the output directory exists (creates recursively).
    # WHY exist_ok=True: concurrent runs of the same command should not race.
    target_path.parent.mkdir(parents=True, exist_ok=True)

    # Serialize using the same contract as seam/cli/output.py:
    # json.dumps(data, ensure_ascii=False) — compact (no indent), no ASCII escaping.
    # A trailing newline is added for shell compatibility (jq, wc -l, etc.).
    content = json.dumps(data, ensure_ascii=False) + "\n"
    content_bytes = content.encode()

    # Atomic write: write to a temp file in the same directory, then replace.
    tmp_path_str: str | None = None
    try:
        fd, tmp_path_str = tempfile.mkstemp(
            suffix=".tmp",
            prefix=".seam_out_",
            dir=target_path.parent,
        )
        with os.fdopen(fd, "wb") as fh:
            fh.write(content_bytes)
        # os.replace is atomic on POSIX; on Windows it is not but it is the best
        # available option and it overwrites the target if it exists.
        os.replace(tmp_path_str, target_path)
        tmp_path_str = None  # Signal that cleanup is no longer needed
    except Exception:
        # Clean up the temp file if the replace failed.
        if tmp_path_str is not None:
            try:
                os.unlink(tmp_path_str)
            except OSError:
                pass
        raise  # Re-raise so the caller can emit an error envelope

    return ToFileResult(
        path=target_path,
        bytes=len(content_bytes),
        summary=summarize(data, command),
    )


def _resolve_target_path(
    command: str,
    label: str,
    out_dir: Path,
    path_override: Path | None,
) -> Path:
    """Compute the resolved target file path.

    Logic:
      1. If path_override is None → auto filename inside out_dir.
      2. If path_override is an existing directory → auto filename inside it.
      3. If path_override ends with a path separator → treat as directory.
      4. Otherwise → use path_override as the exact target file.

    WHY the separator check (#3):
      Allows --to-file /tmp/mydir/ to auto-create the directory and place the
      file inside it, even before the directory exists (common agent pattern).
    """
    safe_label = _sanitize_label(label)
    auto_name = f"{command}-{safe_label}.json"

    if path_override is None:
        return out_dir / auto_name

    override_str = str(path_override)
    is_dir_hint = override_str.endswith(os.sep) or override_str.endswith("/")

    if path_override.is_dir() or is_dir_hint:
        # Strip the trailing separator to get the real directory path
        parent = Path(override_str.rstrip("/\\")) if is_dir_hint else path_override
        return parent / auto_name

    return path_override


def _sanitize_label(label: str) -> str:
    """Replace unsafe filename characters and cap length.

    WHY dots are replaced:
      A dot in the label (e.g. Class.method) would produce double extensions
      (impact-Class.method.json) and could confuse tools that split on the last
      dot. Replacing with _ keeps the label readable (impact-Class_method.json).

    WHY path separators are replaced:
      Slashes / backslashes would make the "filename" into a path fragment and
      allow a caller to escape out_dir. Replacing prevents path traversal.

    WHY length cap:
      Some symbols have very long qualified names. Keeping the label under
      _MAX_LABEL_LEN ensures the full filename stays under the 255-char FS limit
      (command prefix + "-" + label + ".json" ~ 130 + label at 120 = well under).
    """
    if not label:
        return "output"

    # Replace all unsafe chars (path separators, dots, reserved chars, whitespace)
    sanitized = _UNSAFE_LABEL_RE.sub("_", label)

    # Collapse multiple consecutive underscores into one (cleaner filename)
    sanitized = re.sub(r"_+", "_", sanitized)

    # Strip leading/trailing underscores (e.g. from a label like "./foo")
    sanitized = sanitized.strip("_")

    # Cap length
    if len(sanitized) > _MAX_LABEL_LEN:
        sanitized = sanitized[:_MAX_LABEL_LEN]

    # Final guard: empty after sanitization (e.g. label was "..." or "///")
    if not sanitized:
        sanitized = "output"

    return sanitized
